#!/usr/bin/env python3
"""
hybrid_agentic_pipeline.py (Enterprise Edition v3.0 - Strict Zero-Leakage)
========================================================================
Production-Grade End-to-End Hybrid Forecasting Engine:
Fuses Large Language Models (Gemini / OpenAI / Heuristic),
Exa Neural Search, and Google Research's TimesFM 3.0 Foundation Model.

Strict Zero-Leakage Protocol (Enabled in --mode backtest):
1. Automated Blind-Box Entity Masking (Strips ticker, company names, executive names)
2. Relative Temporal Masking (Masks calendar years to [Year_T], [Year_T-1], etc.)
3. Mandatory 3-Branch Scenario Tree (Bear: 25%, Base: 50%, Bull: 25%)
4. Multi-Path Scenario Envelope Execution & Ground-Truth Coverage Metrics
"""

import argparse
import datetime
import json
import os
import re
import sys
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import numpy as np
import pandas as pd
import pypdf
import yfinance as yf

# Optional Torch & TimesFM 3.0
try:
    import torch
    HAS_TORCH = True
except ImportError:
    HAS_TORCH = False

try:
    from timesfm3 import TimesFM3Forecaster
    HAS_TIMESFM = True
except ImportError:
    HAS_TIMESFM = False

# Optional Exa
try:
    from exa_py import Exa
    HAS_EXA = True
except ImportError:
    HAS_EXA = False

# Optional OpenAI & Gemini
try:
    from google import genai
    HAS_GEMINI = True
except ImportError:
    HAS_GEMINI = False

try:
    import openai
    HAS_OPENAI = True
except ImportError:
    HAS_OPENAI = False

# Statement-driven scenario builder and honest volatility forecaster
try:
    from scenario_builder import build_scenarios
except ImportError:
    try:
        from MULTI_AGENT_SANDBOX.scenario_builder import build_scenarios
    except ImportError:
        build_scenarios = None

try:
    from covfree_forecaster import forecast_covfree, annualized_vol
except ImportError:
    try:
        from MULTI_AGENT_SANDBOX.covfree_forecaster import forecast_covfree, annualized_vol
    except ImportError:
        forecast_covfree = None
        annualized_vol = None

try:
    from institutional_engine import build_institutional_scorecard
except ImportError:
    try:
        from MULTI_AGENT_SANDBOX.institutional_engine import build_institutional_scorecard
    except ImportError:
        build_institutional_scorecard = None




def parse_arguments():
    parser = argparse.ArgumentParser(description="Strict Zero-Leakage Hybrid LLM + Exa + TimesFM 3.0 Forecasting Pipeline")
    parser.add_argument("--check", action="store_true",
                        help="Run environment health-check (GPU, CUDA, PyTorch, TimesFM 3.0, API keys) and exit")
    parser.add_argument("--mode", type=str, default="live", choices=["backtest", "live"],
                        help="Operating mode: 'backtest' (strict zero-leakage) or 'live' (real-time forward)")
    parser.add_argument("--tickers", type=str, default="MODISONLTD.NS",
                        help="Comma-separated ticker list (e.g. 'MODISONLTD.NS,CUPID.NS') or path to .txt file")
    parser.add_argument("--pdf", type=str, default=None,
                        help="Path to corporate filing PDF (single file) OR directory containing PDFs")
    parser.add_argument("--scenario", type=str, default=None,
                        help="Path to scenario JSON generated by an Agent Harness (Antigravity, Claude Code, Codex). Bypasses external LLM API calls.")
    parser.add_argument("--cutoff", type=str, default=None,
                        help="Point-in-Time Cutoff Date (YYYY-MM-DD). Strictly required if mode='backtest'")
    parser.add_argument("--horizon", type=int, default=30,
                        help="Forecast horizon in trading days")
    parser.add_argument("--api_provider", type=str, default="nvidia", choices=["nvidia", "gemini", "openai", "heuristic"],
                        help="LLM provider for semantic document reasoning (default: nvidia moonshotai/kimi-k3)")
    parser.add_argument("--api_key", type=str, default=None,
                        help="API Key for LLM provider (defaults to NVIDIA_API_KEY / GEMINI_API_KEY / OPENAI_API_KEY)")
    parser.add_argument("--exa_key", type=str, default=None,
                        help="API Key for Exa Neural Search (defaults to EXA_API_KEY env var)")
    parser.add_argument("--output_dir", type=str, default="./hybrid_output",
                        help="Directory to save forecast JSON datasets and visualization charts")
    return parser.parse_args()


# ==============================================================================
# Diagnostics & Health-Check
# ==============================================================================
def run_diagnostics():
    print("=================================================================")
    print(" SYSTEM & ENVIRONMENT HEALTH-CHECK")
    print("=================================================================")
    cuda_avail = HAS_TORCH and torch.cuda.is_available()
    gpu_name = torch.cuda.get_device_name(0) if cuda_avail else "None (CPU Mode)"

    print(f"• PyTorch:               {'✓ Available' if HAS_TORCH else '✗ Missing'}")
    print(f"• CUDA GPU Acceleration: {'✓ Available (' + gpu_name + ')' if cuda_avail else '✗ No GPU detected'}")
    print(f"• Google TimesFM 3.0:    {'✓ Available' if HAS_TIMESFM else '✗ Missing (run pip install git+https://github.com/google-research/timesfm.git)'}")
    print(f"• Exa Neural Search:     {'✓ Available' if HAS_EXA else '✗ Missing'}")
    print(f"• Google GenAI SDK:      {'✓ Available' if HAS_GEMINI else '✗ Missing'}")
    print(f"• OpenAI SDK:            {'✓ Available' if HAS_OPENAI else '✗ Missing'}")
    print(f"• PyPDF Document Parser: {'✓ Available' if 'pypdf' in sys.modules else '✗ Missing'}")

    print("\nAPI Keys Detected in Environment:")
    print(f"• GEMINI_API_KEY:        {'✓ Set' if os.environ.get('GEMINI_API_KEY') else '✗ Not set'}")
    print(f"• EXA_API_KEY:           {'✓ Set' if os.environ.get('EXA_API_KEY') else '✗ Not set'}")
    print(f"• OPENAI_API_KEY:        {'✓ Set' if os.environ.get('OPENAI_API_KEY') else '✗ Not set'}")
    print("=================================================================\n")


# ==============================================================================
# Strict Zero-Leakage Sanitizer
# ==============================================================================
def anonymize_text_for_backtest(raw_text: str, ticker: str, cutoff_date: str) -> str:
    """Strips company names, tickers, and relative dates to eliminate LLM pre-training memory leakage."""
    sanitized = raw_text
    clean_ticker = ticker.replace(".NS", "").replace(".BO", "")

    # Common company name patterns
    name_patterns = [
        clean_ticker,
        r"Hero\s+MotoCorp", r"Hero\s+Honda", r"Hero",
        r"Cupid\s+Limited", r"Cupid",
        r"Modison\s+Metals", r"Modison\s+Limited", r"Modison",
        r"Reliance\s+Industries", r"Reliance",
        r"Tata\s+Motors", r"Tata\s+Consultancy", r"TCS"
    ]
    for pat in name_patterns:
        sanitized = re.sub(rf"\b{pat}\b", "[Target_Company_Alpha]", sanitized, flags=re.IGNORECASE)

    # Relative Year Masking
    if cutoff_date:
        cutoff_year = int(cutoff_date[:4])
        for y_offset in range(-5, 6):
            target_y = cutoff_year + y_offset
            if y_offset == 0:
                rep = "[Year_T]"
            elif y_offset < 0:
                rep = f"[Year_T{y_offset}]"
            else:
                rep = f"[Year_T+{y_offset}]"
            sanitized = re.sub(rf"\b{target_y}\b", rep, sanitized)

    return sanitized


# ==============================================================================
# 1. Multi-Modal Data Ingestion Layer (Market + Exa + Smart PDF)
# ==============================================================================
def resolve_tickers(ticker_arg: str) -> list:
    if os.path.isfile(ticker_arg):
        with open(ticker_arg) as f:
            return [line.strip() for line in f if line.strip() and not line.startswith("#")]
    return [t.strip() for t in ticker_arg.split(",") if t.strip()]


def resolve_pdf_for_ticker(pdf_arg: str, ticker_symbol: str) -> str:
    if not pdf_arg or not os.path.exists(pdf_arg):
        return ""
    if os.path.isfile(pdf_arg):
        return pdf_arg
    if os.path.isdir(pdf_arg):
        clean_name = ticker_symbol.replace(".NS", "").replace(".BO", "").lower()
        for fname in os.listdir(pdf_arg):
            if fname.lower().endswith(".pdf") and clean_name in fname.lower():
                return os.path.join(pdf_arg, fname)
    return ""


def fetch_market_data(ticker_symbol: str, mode: str, cutoff_date: str, horizon: int):
    print(f"\n[Market Ingestion] Fetching {ticker_symbol} (Mode: {mode})...")
    ticker = yf.Ticker(ticker_symbol)
    df = ticker.history(period="max")
    df.index = pd.to_datetime(df.index).tz_localize(None)
    df.dropna(subset=["Close"], inplace=True)
    df["Date_str"] = df.index.strftime("%Y-%m-%d")

    if df.empty:
        raise ValueError(f"No price data found for {ticker_symbol}")

    if mode == "backtest":
        if not cutoff_date:
            raise ValueError("In 'backtest' mode, --cutoff YYYY-MM-DD is strictly required!")
        train_df = df[df["Date_str"] <= cutoff_date].copy()
        test_df = df[df["Date_str"] > cutoff_date].iloc[:horizon].copy()
        if train_df.empty:
            raise ValueError(f"No data on or before {cutoff_date} for {ticker_symbol}")
        last_price = float(train_df.iloc[-1]["Close"])
    else:  # Live mode
        train_df = df.copy()
        test_df = pd.DataFrame()
        last_price = float(train_df.iloc[-1]["Close"])

    print(f"  • Ingested {len(train_df)} training sessions. Last Price: Rs. {last_price:.2f}")
    return train_df, test_df, last_price


def fetch_exa_intelligence(ticker_symbol: str, exa_api_key: str, mode: str, cutoff_date: str) -> dict:
    exa_key = exa_api_key or os.environ.get("EXA_API_KEY")
    if not HAS_EXA or not exa_key:
        print("  • Exa Search: Skipped (no API key or exa_py not installed).")
        return {"summary": "No Exa search performed", "catalysts": []}

    print(f"\n[Exa Search] Querying live neural search for {ticker_symbol}...")
    try:
        exa = Exa(exa_key)
        company_query = ticker_symbol.replace(".NS", "").replace(".BO", "")
        if mode == "live":
            query = f"{company_query} latest earnings corporate announcements expansion orders"
        else:
            query = f"{company_query} corporate announcements acquisition capacity {cutoff_date[:4]}"

        res = exa.search(query, num_results=3)
        catalysts = [{"title": r.title, "url": r.url} for r in res.results]
        print(f"  • Exa discovered {len(catalysts)} corporate events/announcements.")
        return {"summary": f"Exa Neural Search for {company_query}", "catalysts": catalysts}
    except Exception as e:
        print(f"  • Exa Search Warning: {e}")
        return {"summary": "Exa query failed", "catalysts": []}


def extract_filing_pdf(pdf_path: str, max_pages: int = 40) -> str:
    if not pdf_path or not os.path.exists(pdf_path):
        return ""
    print(f"\n[PDF Ingestion] Parsing filing: {pdf_path} (First {max_pages} pages)...")
    reader = pypdf.PdfReader(pdf_path)
    text = []
    for i in range(min(len(reader.pages), max_pages)):
        t = reader.pages[i].extract_text()
        if t:
            text.append(f"--- PAGE {i+1} ---\n" + t)
    extracted = "\n".join(text)
    print(f"  • Extracted {len(extracted)} characters from PDF.")
    return extracted


# ==============================================================================
# 2. LLM Semantic Reasoning Layer (with Strict Zero-Leakage Anonymizer)
# ==============================================================================
def synthesize_fundamental_valuation(ticker: str, filing_text: str, exa_data: dict, current_price: float,
                                     provider: str, api_key: str, horizon: int, mode: str, cutoff_date: str) -> dict:
    # 1. Enforce Zero-Leakage Sanitization in Backtest Mode
    if mode == "backtest":
        print(f"\n[Zero-Leakage Sanitizer] Anonymizing entity identifiers for {ticker} (Cutoff: {cutoff_date})...")
        effective_text = anonymize_text_for_backtest(filing_text, ticker, cutoff_date)
        display_name = "[Target_Company_Alpha]"
        temporal_context = f"[Year_T] (Strict Cutoff: {cutoff_date})"
        zero_leak_instruction = """STRICT ZERO-LEAKAGE BACKTEST INSTRUCTION:
You are an objective forensic quant evaluator performing a BLIND-BOX valuation analysis.
You have NO knowledge of this asset's real-world name, ticker, or performance after [Year_T].
Reason PURELY on the provided balance sheet, historical margins, and peer multiples.
You MUST output a 3-branch scenario tree:
- Bear Case (25% prob): Multiple de-rating / margin compression
- Base Case (50% prob): Historical mean multiple / steady growth
- Bull Case (25% prob): Multiple expansion to peer parity
"""
    else:
        effective_text = filing_text
        display_name = ticker
        temporal_context = "Present Real-Time Live Market"
        zero_leak_instruction = "Live forward forecasting. Full real-world context enabled."

    print(f"[LLM Valuation Layer] Reasoning over fundamentals for {display_name} ({temporal_context})...")

    # NVIDIA NIM LLM / Scenario Builder Engine / Heuristic Mode
    if provider in ["nvidia", "heuristic"] or (not api_key and not os.environ.get("GEMINI_API_KEY") and not os.environ.get("OPENAI_API_KEY")):
        fund_res = None
        if build_scenarios is not None:
            try:
                fund_res = build_scenarios(ticker, current_price=current_price, as_of=cutoff_date, use_llm=True)
            except Exception as e:
                print(f"  • scenario_builder notice: {e}. Falling back to statement regex.")

        if fund_res:
            eps = fund_res["eps"]
            sector_pe = fund_res["sector_pe"]
            trailing_pe = current_price / eps if eps > 0 else 20.0
            scenarios = fund_res["scenarios"]
            weighted_tgt = fund_res["weighted_target"]
            src = fund_res.get("source", "scenario_builder")
            thesis = fund_res.get("thesis", "")
            print(f"  • Fundamental Scenarios (via {src}, EPS={eps:.2f}, Sector P/E={sector_pe:.1f}):")
            if thesis:
                print(f"    Qualitative Thesis: \"{thesis}\"")
            print(f"    Bear ({scenarios['bear']['probability']*100:.0f}%) = Rs. {scenarios['bear']['target_price']:.2f} | Base ({scenarios['base']['probability']*100:.0f}%) = Rs. {scenarios['base']['target_price']:.2f} | Bull ({scenarios['bull']['probability']*100:.0f}%) = Rs. {scenarios['bull']['target_price']:.2f}")
            print(f"    Expected Weighted Target = Rs. {weighted_tgt:.2f}")
            if mode != "backtest":
                scenarios = None
        else:
            eps_match = re.search(r"(?:Diluted EPS|EPS)[^\d]*([\d,]+\.?\d*)", effective_text, re.IGNORECASE)
            eps = float(eps_match.group(1).replace(",", "")) if eps_match else max(1.0, current_price / 20.0)
            trailing_pe = current_price / eps
            sector_pe = 38.0

            if mode == "backtest":
                # Formulate 3 discrete scenarios
                bear_tgt = eps * 16.0
                base_tgt = eps * 22.0
                bull_tgt = eps * 27.5
                weighted_tgt = (0.25 * bear_tgt) + (0.50 * base_tgt) + (0.25 * bull_tgt)

                scenarios = {
                    "bear": {"probability": 0.25, "target_price": bear_tgt, "target_pe": 16.0},
                    "base": {"probability": 0.50, "target_price": base_tgt, "target_pe": 22.0},
                    "bull": {"probability": 0.25, "target_price": bull_tgt, "target_pe": 27.5}
                }
                print(f"  • Heuristic Scenarios: Bear = Rs. {bear_tgt:.2f} | Base = Rs. {base_tgt:.2f} | Bull = Rs. {bull_tgt:.2f}")
                print(f"  • Expected Weighted Target = Rs. {weighted_tgt:.2f}")
            else:
                target_multiple = min(sector_pe * 0.60, max(18.0, trailing_pe * 1.5))
                weighted_tgt = eps * target_multiple
                scenarios = None

        return {
            "trailing_eps": eps,
            "trailing_pe": trailing_pe,
            "sector_pe": sector_pe,
            "fair_value_target": weighted_tgt,
            "scenarios": scenarios,
            "sigmoid_steepness": 0.18,
            "sigmoid_midpoint": horizon / 2.0,
            "is_anonymized": (mode == "backtest")
        }

    # Gemini API
    elif provider == "gemini":
        gemini_key = api_key or os.environ.get("GEMINI_API_KEY")
        try:
            from google import genai
            client = genai.Client(api_key=gemini_key)
            prompt = f"""{zero_leak_instruction}

Target Asset: {display_name}
Current Market Price: {current_price}
Forecast Horizon: {horizon} trading days.

Disclosures Excerpt:
{effective_text[:12000]}

Calculate trailing EPS, trailing P/E, and sector peer multiple.
Output 3 probabilistic scenarios (bear 25%, base 50%, bull 25%) and sigmoid parameters.
Return ONLY valid JSON:
{{
  "trailing_eps": float,
  "trailing_pe": float,
  "sector_pe": float,
  "scenarios": {{
    "bear": {{"probability": 0.25, "target_price": float, "target_pe": float}},
    "base": {{"probability": 0.50, "target_price": float, "target_pe": float}},
    "bull": {{"probability": 0.25, "target_price": float, "target_pe": float}}
  }},
  "sigmoid_steepness": float,
  "sigmoid_midpoint": float
}}
"""
            res = client.models.generate_content(
                model="gemini-2.5-flash",
                contents=prompt,
                config={"response_mime_type": "application/json"}
            )
            data = json.loads(res.text)
            if "scenarios" in data and "base" in data["scenarios"]:
                data["fair_value_target"] = sum(s["probability"] * s["target_price"] for s in data["scenarios"].values())
            data["is_anonymized"] = (mode == "backtest")
            return data
        except Exception as e:
            print(f"  • Gemini API Error: {e}. Falling back to heuristic.")
            return synthesize_fundamental_valuation(ticker, filing_text, exa_data, current_price, "heuristic", None, horizon, mode, cutoff_date)

    # OpenAI API
    elif provider == "openai":
        openai_key = api_key or os.environ.get("OPENAI_API_KEY")
        try:
            import openai
            client = openai.OpenAI(api_key=openai_key)
            prompt = f"""{zero_leak_instruction}
Target Asset: {display_name}
Current Market Price: {current_price}
Forecast Horizon: {horizon} trading days.

Disclosures Excerpt:
{effective_text[:12000]}

Return strict JSON:
{{
  "trailing_eps": float,
  "trailing_pe": float,
  "sector_pe": float,
  "scenarios": {{
    "bear": {{"probability": 0.25, "target_price": float, "target_pe": float}},
    "base": {{"probability": 0.50, "target_price": float, "target_pe": float}},
    "bull": {{"probability": 0.25, "target_price": float, "target_pe": float}}
  }},
  "sigmoid_steepness": float,
  "sigmoid_midpoint": float
}}
"""
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[
                    {"role": "system", "content": "You are a quantitative valuation analyst. Return strict JSON only."},
                    {"role": "user", "content": prompt}
                ],
                response_format={"type": "json_object"}
            )
            data = json.loads(response.choices[0].message.content)
            if "scenarios" in data and "base" in data["scenarios"]:
                data["fair_value_target"] = sum(s["probability"] * s["target_price"] for s in data["scenarios"].values())
            data["is_anonymized"] = (mode == "backtest")
            return data
        except Exception as e:
            print(f"  • OpenAI API Error: {e}. Falling back to heuristic.")
            return synthesize_fundamental_valuation(ticker, filing_text, exa_data, current_price, "heuristic", None, horizon, mode, cutoff_date)


# ==============================================================================
# 3. Vectorized Dynamic Covariate Construction & TimesFM 3.0 Inference
# ==============================================================================
def execute_hybrid_forecaster(batch_train_dfs: list, batch_valuations: list, horizon: int):
    batch_size = len(batch_train_dfs)
    print(f"\n[TimesFM 3.0 Engine] Preparing Batch Inference (Batch Size: {batch_size}, Horizon: {horizon})...")

    ctx_len = min(64, min(len(df) for df in batch_train_dfs))

    batch_contexts = []
    batch_past_only = []
    batch_past_future = []

    for i in range(batch_size):
        df = batch_train_dfs[i].iloc[-ctx_len:]
        val_data = batch_valuations[i]
        last_price = float(df.iloc[-1]["Close"])
        target_price = val_data["fair_value_target"]
        k = val_data.get("sigmoid_steepness", 0.18)
        t0 = val_data.get("sigmoid_midpoint", horizon / 2.0)

        batch_contexts.append(df["Close"].values.astype(np.float32))

        vol = df["Volume"].values.astype(np.float32)
        vol_sma = pd.Series(vol).rolling(20, min_periods=1).mean().values
        vol_ratio = np.where(vol_sma > 0, vol / vol_sma, 1.0).astype(np.float32)
        batch_past_only.append(vol_ratio)

        cov_path = np.zeros(ctx_len + horizon, dtype=np.float32)
        cov_path[:ctx_len] = (df["Close"].values - last_price) / 100.0
        if forecast_covfree is not None:
            try:
                ann_vol = annualized_vol(df["Close"]) if annualized_vol else 0.25
                p_proj, _, _ = forecast_covfree(last_price, target_price, ann_vol, horizon)
                cov_path[ctx_len:] = (p_proj - last_price) / 100.0
            except Exception:
                for h in range(horizon):
                    step = h + 1
                    progress = 1.0 / (1.0 + np.exp(-k * (step - t0)))
                    projected = last_price + progress * (target_price - last_price)
                    cov_path[ctx_len + h] = (projected - last_price) / 100.0
        else:
            for h in range(horizon):
                step = h + 1
                progress = 1.0 / (1.0 + np.exp(-k * (step - t0)))
                projected = last_price + progress * (target_price - last_price)
                cov_path[ctx_len + h] = (projected - last_price) / 100.0
        batch_past_future.append(cov_path)

    device = "cuda" if (HAS_TORCH and torch.cuda.is_available()) else "cpu"
    print(f"  • Running TimesFM 3.0 on {device}...")

    if HAS_TIMESFM:
        forecaster = TimesFM3Forecaster.from_pretrained("google/timesfm-3.0-pytorch", device=device)
        batch_results = list(forecaster.predict_batch(
            contexts=batch_contexts,
            horizon=horizon,
            past_only_covariates=batch_past_only,
            past_future_covariates=batch_past_future,
            padding_mode="edge",
            return_quantiles=True,
            make_positive=True
        ))
        preds = np.array([r.forecast[:horizon].astype(float) for r in batch_results])
        q10s = np.array([r.quantiles[:horizon, 0].astype(float) for r in batch_results])
        q90s = np.array([r.quantiles[:horizon, 8].astype(float) for r in batch_results])
    else:
        preds = []
        q10s = []
        q90s = []
        for i in range(batch_size):
            last_p = float(batch_train_dfs[i].iloc[-1]["Close"])
            tgt_p = batch_valuations[i]["fair_value_target"]
            c_series = batch_train_dfs[i]["Close"]
            ann_vol = 0.25
            if annualized_vol is not None:
                try:
                    ann_vol = annualized_vol(c_series)
                    if np.isnan(ann_vol) or ann_vol <= 0:
                        ann_vol = 0.25
                except Exception:
                    ann_vol = 0.25
            p = None
            if forecast_covfree is not None:
                try:
                    p, q10, q90 = forecast_covfree(last_p, tgt_p, ann_vol, horizon)
                except Exception as ex:
                    print(f"  • forecast_covfree fallback notice: {ex}")
            if p is None:
                k = batch_valuations[i].get("sigmoid_steepness", 0.18)
                t0 = batch_valuations[i].get("sigmoid_midpoint", horizon / 2.0)
                p = np.array([last_p + (1.0 / (1.0 + np.exp(-k * (h + 1 - t0)))) * (tgt_p - last_p) for h in range(horizon)])
                q10 = p * 0.90
                q90 = p * 1.10
            preds.append(p)
            q10s.append(q10)
            q90s.append(q90)
        preds = np.array(preds)
        q10s = np.array(q10s)
        q90s = np.array(q90s)

    return preds, q10s, q90s


# ==============================================================================
# 4. Visualization & Output Reporting
# ==============================================================================
def export_and_plot_results(output_dir: str, tickers: list, batch_train_dfs: list, batch_test_dfs: list,
                           batch_valuations: list, preds: np.ndarray, q10s: np.ndarray, q90s: np.ndarray,
                           mode: str, horizon: int):
    os.makedirs(output_dir, exist_ok=True)
    summary_catalog = []

    for i, ticker in enumerate(tickers):
        train_df = batch_train_dfs[i]
        test_df = batch_test_dfs[i]
        val_data = batch_valuations[i]
        pred = preds[i]
        q10 = q10s[i]
        q90 = q90s[i]
        last_price = float(train_df.iloc[-1]["Close"])

        last_date = train_df.index[-1]
        future_dates = [last_date + datetime.timedelta(days=d) for d in range(1, horizon + 1)]

        plt.figure(figsize=(14, 7), dpi=150)
        plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')
        plt.plot(train_df.index[-40:], train_df["Close"].values[-40:], label="Historical Context", color="#1b365d", linewidth=2)
        plt.plot(future_dates, pred, label=f"Hybrid Weighted Forecast (Target: Rs. {val_data['fair_value_target']:.2f})", color="#6b29b2", linewidth=2.8)

        # Plot Scenarios if available
        if val_data.get("scenarios"):
            sc = val_data["scenarios"]
            k = val_data.get("sigmoid_steepness", 0.18)
            t0 = val_data.get("sigmoid_midpoint", horizon / 2.0)
            bear_path = [last_price + (1.0 / (1.0 + np.exp(-k * (h + 1 - t0)))) * (sc["bear"]["target_price"] - last_price) for h in range(horizon)]
            bull_path = [last_price + (1.0 / (1.0 + np.exp(-k * (h + 1 - t0)))) * (sc["bull"]["target_price"] - last_price) for h in range(horizon)]
            plt.plot(future_dates, bull_path, label=f"Bull Scenario (25% prob): Rs. {sc['bull']['target_price']:.0f}", color="#107c41", linestyle="-.", linewidth=1.8)
            plt.plot(future_dates, bear_path, label=f"Bear Scenario (25% prob): Rs. {sc['bear']['target_price']:.0f}", color="#d83b01", linestyle=":", linewidth=1.8)
            plt.fill_between(future_dates, bear_path, bull_path, color="#0078d4", alpha=0.10, label="Strict Scenario Envelope")
        else:
            plt.fill_between(future_dates, q10, q90, color="#6b29b2", alpha=0.15, label="80% Prediction Band (P10 - P90)")

        coverage_str = ""
        if mode == "backtest" and not test_df.empty:
            actuals = test_df["Close"].values[:len(pred)]
            actual_dates = test_df.index[:len(pred)]
            plt.plot(actual_dates, actuals, label="Actual Ground Truth Prices", color="#107c41", linewidth=2.5, marker="o", markersize=3)
            
            valid_mask = ~np.isnan(actuals) & ~np.isnan(pred[:len(actuals)])
            if valid_mask.any():
                clean_act = actuals[valid_mask]
                clean_pr = pred[:len(actuals)][valid_mask]
                mae = float(np.mean(np.abs(clean_pr - clean_act)))
                mape = float(np.mean(np.abs((clean_act - clean_pr) / clean_act)) * 100)
                metric_str = f"MAE: Rs. {mae:.2f} | MAPE: {mape:.2f}%"
            else:
                mae, mape = 0.0, 0.0
                metric_str = "Backtest (No valid ground truth ticks)"

            if val_data.get("scenarios"):
                in_env = np.sum((clean_act >= np.array(bear_path)[:len(clean_act)] * 0.90) & (clean_act <= np.array(bull_path)[:len(clean_act)] * 1.10))
                cov_pct = float((in_env / len(clean_act)) * 100)
                coverage_str = f" | Envelope Coverage: {cov_pct:.1f}%"
        else:
            mae, mape = None, None
            metric_str = "Live Forward Prediction"

        # Institutional Scorecard
        scorecard = None
        stop_loss_val = None
        if build_institutional_scorecard is not None:
            try:
                fund_d = {
                    "scenarios": val_data.get("scenarios") or {},
                    "weighted_target": val_data.get("fair_value_target", last_price),
                    "eps": val_data.get("trailing_eps"),
                    "sector_pe": val_data.get("sector_pe", 22.0)
                }
                try:
                    tk = yf.Ticker(ticker)
                    fund_d["industry"] = tk.info.get("industry") or tk.info.get("sector") or "General"
                except Exception:
                    fund_d["industry"] = "General"

                scorecard = build_institutional_scorecard(
                    ticker=ticker,
                    last_price=last_price,
                    fundamental_data=fund_d,
                    forecast_results={
                        "numerical_context": train_df["Close"].values[-64:].tolist() if not train_df.empty else [last_price]*10,
                        "weighted_expected": pred.tolist() if isinstance(pred, np.ndarray) else pred,
                        "base_q10": q10.tolist() if isinstance(q10, np.ndarray) else q10,
                        "base_q90": q90.tolist() if isinstance(q90, np.ndarray) else q90
                    },
                    horizon=horizon,
                    as_of=train_df.index[-1].strftime("%Y-%m-%d") if not train_df.empty else None
                )
                stop_loss_val = scorecard["institutional_risk_and_sizing"]["stop_loss_invalidation_level"]
            except Exception as e:
                print(f"  • [{ticker}] institutional_scorecard notice: {e}")

        anon_badge = "[BLIND-BOX ZERO LEAKAGE]" if mode == "backtest" else "[LIVE FORWARD]"
        if stop_loss_val:
            plt.axhline(y=stop_loss_val, color="#ea4335", linestyle="--", linewidth=1.8, label=f"Institutional Invalidation Stop (Rs. {stop_loss_val:.2f})")

        plt.title(f"{ticker} — Hybrid LLM + TimesFM 3.0 {anon_badge}\n{metric_str}{coverage_str}", fontsize=12, fontweight="bold")
        plt.xlabel("Date", fontsize=10, fontweight="bold")
        plt.ylabel("Price (INR)", fontsize=10, fontweight="bold")
        plt.legend(loc="upper left")
        plt.tight_layout()

        plot_path = os.path.join(output_dir, f"{ticker}_forecast_plot.png")
        plt.savefig(plot_path)
        plt.close()

        record = {
            "ticker": ticker,
            "mode": mode,
            "is_anonymized": (mode == "backtest"),
            "last_price": last_price,
            "fundamental_valuation": val_data,
            "terminal_prediction": float(pred[-1]),
            "p10_terminal": float(q10[-1]),
            "p90_terminal": float(q90[-1]),
            "plot_saved": plot_path
        }
        if mode == "backtest" and not test_df.empty:
            record["metrics"] = {"mae": mae, "mape": mape}
            if val_data.get("scenarios"):
                record["envelope_coverage_pct"] = cov_pct
        if scorecard:
            record["institutional_scorecard"] = scorecard

        json_path = os.path.join(output_dir, f"{ticker}_forecast_results.json")
        with open(json_path, "w") as f:
            json.dump(record, f, indent=2)

        summary_catalog.append(record)
        print(f"  • [{ticker}] Plot -> {plot_path}")
        print(f"  • [{ticker}] JSON -> {json_path}")
        if scorecard:
            print(f"  • [{ticker}] Institutional Directive: {scorecard['institutional_risk_and_sizing']['institutional_directive']}")

    summary_path = os.path.join(output_dir, "batch_portfolio_summary.json")
    with open(summary_path, "w") as f:
        json.dump(summary_catalog, f, indent=2)
    print(f"\n[Done] All batch results and plots saved to {output_dir}!")


def main():
    args = parse_arguments()

    if args.check:
        run_diagnostics()
        sys.exit(0)

    tickers = resolve_tickers(args.tickers)
    print(f"=================================================================")
    print(f" HYBRID LLM + EXA + TIMESFM 3.0 FORECASTING ENGINE")
    print(f" Mode: {args.mode.upper()} | Tickers: {len(tickers)} | Horizon: {args.horizon} days")
    if args.mode == "backtest":
        print(f" Zero-Leakage: ACTIVE (Blind-Box Entity Masking + 3-Branch Scenario Tree)")
    print(f"=================================================================")

    # Load Agent Harness Scenario if provided (Non-API Hybrid Mode)
    scenario_data = {}
    if args.scenario and os.path.exists(args.scenario):
        with open(args.scenario) as f:
            scenario_data = json.load(f)
        print(f"\n[Agent Harness Non-API Mode] Loaded external scenario: {args.scenario}")

    batch_train_dfs = []
    batch_test_dfs = []
    batch_valuations = []

    for ticker in tickers:
        train_df, test_df, last_price = fetch_market_data(ticker, args.mode, args.cutoff, args.horizon)
        
        if args.scenario and (ticker in scenario_data or "fair_value_target" in scenario_data):
            val_data = scenario_data.get(ticker, scenario_data)
            print(f"  • Using Agent Harness Scenario for {ticker}: Fair Value Target = Rs. {val_data['fair_value_target']:.2f}")
        else:
            exa_data = fetch_exa_intelligence(ticker, args.exa_key, args.mode, args.cutoff)
            pdf_path = resolve_pdf_for_ticker(args.pdf, ticker)
            filing_text = extract_filing_pdf(pdf_path)
            val_data = synthesize_fundamental_valuation(ticker, filing_text, exa_data, last_price,
                                                        args.api_provider, args.api_key, args.horizon,
                                                        args.mode, args.cutoff)

        batch_train_dfs.append(train_df)
        batch_test_dfs.append(test_df)
        batch_valuations.append(val_data)

    preds, q10s, q90s = execute_hybrid_forecaster(batch_train_dfs, batch_valuations, args.horizon)
    export_and_plot_results(args.output_dir, tickers, batch_train_dfs, batch_test_dfs,
                           batch_valuations, preds, q10s, q90s, args.mode, args.horizon)


if __name__ == "__main__":
    main()
